[package]
name = "orbita-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Rust SDK for orbita node authors"
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
orbita-core.workspace = true
orbita-sdk-macros.workspace = true
orbita-workflow.workspace = true
semver = "1"

[lints]
workspace = true
