[package]
name = "logika-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Workflow runtime for logika"
publish = false

[dependencies]
logika-core.workspace = true
logika-workflow.workspace = true
semver = "1"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tokio-util = "0.7"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
