[package]
name = "logika-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Node and plugin registry for logika"
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
logika-core.workspace = true
logika-workflow.workspace = true
semver = "1"

[lints]
workspace = true
